### ISSUE TITLE
eslint plugin peerDep warnings return

### ISSUE THREAD

**Issue by jasonkarns** [standard/standard#1026]
#255 returns :(

Using npm 5.5.1 and latest standard (10.0.3), I am getting peerDep warnings from some eslint plugins:

```
npm WARN eslint-plugin-import@2.2.0 requires a peer of eslint@2.x - 3.x but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-react@6.10.3 requires a peer of eslint@^2.0.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.
```

Both plugins are only being pulled in by standard:

```
$ npm ls eslint-plugin-import
<pkg>
└─┬ standard@10.0.3
  └── eslint-plugin-import@2.2.0 
$ npm ls eslint-plugin-react
<pkg>
└─┬ standard@10.0.3
  └── eslint-plugin-react@6.10.3 
```

**Comment by Flet** [comment]
Could you give `standard@beta` a try? We just published it and it updates `eslint` and other plugins to their latest versions.

**Comment by jasonkarns** [comment]
@beta fixes it... 👍

**Comment by WalterBoles** [comment]
I'm still cannot get the done.is there someone that can help me

**Comment by WalterBoles** [comment]
Did something happen to my investment and what does it total

**Comment by feross** [comment]
🗣 Standard 11 is released! Run `npm install standard@latest --save-dev` to update to the latest version. This will also update the version in `package.json` ✨

Changelog: https://github.com/standard/standard/blob/master/CHANGELOG.md#1100---2018-02-18
