### ISSUE TITLE
v12.0.1 standard and phpstorm typerror

### ISSUE THREAD

**Issue by AngeIII** [standard/standard#1212]
**What version of standard?**
v12.0.1
**What operating system, Node.js, and npm version?**
node 10.11.0, npm latest
**What did you expect to happen?**
no error in phpstorm
**What actually happened?**
**TypeError: globPattern.startsWith is not a function**

TypeError: globPattern.startsWith is not a function
    at relativize (/home/Data/visualcomposer/node_modules/standard/node_modules/eslint/lib/ignored-paths.js:106:32)
    at IgnoredPaths.addPatternRelativeToCwd (/home/Data/visualcomposer/node_modules/standard/node_modules/eslint/lib/ignored-paths.js:249:15)
    at new IgnoredPaths (/home/Data/visualcomposer/node_modules/standard/node_modules/eslint/lib/ignored-paths.js:232:22)
    at CLIEngine.isPathIgnored (/home/Data/visualcomposer/node_modules/standard/node_modules/eslint/lib/cli-engine.js:638:30)
    at ESLintPlugin.getErrors (/home/Apps/PhpStorm-2018.2.4/PhpStorm-182.4505.42/plugins/JavaScriptLanguage/languageService/eslint/bin/eslint-plugin.js:83:23)
    at ESLintPlugin.onMessage (/home/Apps/PhpStorm-2018.2.4/PhpStorm-182.4505.42/plugins/JavaScriptLanguage/languageService/eslint/bin/eslint-plugin.js:43:33)
    at Interface.<anonymous> (/home/Apps/PhpStorm-2018.2.4/PhpStorm-182.4505.42/plugins/JavaScriptLanguage/jsLanguageServicesImpl/js-language-service.js:105:39)
    at Interface.emit (events.js:182:13)
    at Interface._onLine (readline.js:290:10)
    at Interface._normalWrite (readline.js:433:12)
Process finished with exit code -1

**Comment by LinusU** [comment]
> eslint/lib/ignored-paths.js:106:32

Seems like this is a problem in ESLint, would you mind opening an issue there? ☺️

**Comment by LinusU** [comment]
Should be fixed by #1210 then 👍

**Comment by yf287** [comment]
I used yarn to resolute eslint at 5.6.1,but still get the error.
I tried to update eslint to lastest version by npm either,and it doesn't work yet.
how can i do

**Comment by Manu1400** [comment]
@yf287 see the new eslint ticket: https://github.com/eslint/eslint/issues/11429
